import { existsSync, readdirSync, readFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const VIRTUAL_MODULE_ID = 'virtual:page-registry'
const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_MODULE_ID}`

/**
 * Vite Plugin for Multi-Tenant File Resolution
 * 1. Resolves @page/* to either _tenants/{tenantCode}/* or base/*
 * 2. Generates virtual:page-registry for optimal tree-shaking
 */
export function tenantResolver(moduleDir: string, tenantCode: string) {
  const presentationBase = path.resolve(__dirname, 'src', moduleDir)

  // Helper: resolve path ke tenant atau fallback ke base
  function resolvePath(subPath: string): string | null {
    const extensions = ['.vue', '.ts']
    const findIn = (dir: string) => {
      for (const ext of extensions) {
        const file = path.join(presentationBase, dir, subPath.endsWith(ext) ? subPath : `${subPath}${ext}`).replace(/\\/g, '/')
        if (existsSync(file)) return file
      }
      return null
    }

    if (tenantCode !== 'base') {
      const tenantFile = findIn(`_tenants/${tenantCode}`)
      if (tenantFile) return tenantFile
    }
    return findIn('base')
  }

  // Helper: Ambil list modul aktif dari manifest.ts tenant/base lewat FS
  function getActiveModules(): string[] {
    const manifestPath = resolvePath('manifest')
    if (!manifestPath || !existsSync(manifestPath)) return []

    try {
      const content = readFileSync(manifestPath, 'utf-8')
      // Regex untuk menangkap isi array activeModules = [ ... ]
      const match = content.match(/activeModules\s*=\s*\[([\s\S]*?)\]/)
      if (!match) return []
      
      return match[1]
        .split(',')
        .map(m => m.trim().replace(/['",]/g, ''))
        .filter(Boolean)
    } catch (e) {
      console.error('[TenantResolver] Failed to parse manifest:', e)
      return []
    }
  }

  // Generate kode virtual module secara statis untuk tree-shaking optimal
  function generateRegistry(): string {
    const activeModules = getActiveModules()
    const imports: string[] = []
    const entries: string[] = []

    activeModules.forEach((moduleName, i) => {
      const mainPath = resolvePath(`routes/${moduleName}.routes`)
      const extraPath = resolvePath(`routes/${moduleName}.extra`)

      const mainVar = `main_${i}`
      const extraVar = `extra_${i}`
      const parts: string[] = []

      if (mainPath) {
        imports.push(`import * as ${mainVar} from '${mainPath}';`)
        parts.push(mainVar)
      }
      
      if (extraPath) {
        imports.push(`import * as ${extraVar} from '${extraPath}';`)
        parts.push(extraVar)
      }

      if (parts.length > 0) {
        entries.push(`  "${moduleName}": [${parts.join(', ')}]`)
      }
    })

    return [
      '// Auto-generated by vite-plugin-tenant. DO NOT EDIT.',
      ...imports,
      '',
      `export const moduleLibrary = {\n${entries.join(',\n')}\n};`,
    ].join('\n')
  }

  return {
    name: 'tenant-resolver',

    resolveId(id: string) {
      if (id === VIRTUAL_MODULE_ID) return RESOLVED_VIRTUAL_ID
      if (id.startsWith('@page/')) {
        const page = id.replace('@page/', '')
        return resolvePath(page)
      }
    },

    load(id: string) {
      if (id === RESOLVED_VIRTUAL_ID) {
        return generateRegistry()
      }
    },
  }
}
